### ISSUE TITLE
Request to add references

### ISSUE THREAD

**Issue by zhengying-liu** [j991222/ai4math-papers#1]
Hi thank you for this awesome list!

Our ICLR 2024 spotlight paper is related to theorem synthesis:

_MUSTARD: Mastering Uniform Synthesis of Theorem and Proof Data_
https://openreview.net/forum?id=8xliOUg9EW

Our NAACL 2024 findings paper is also related to theorem generation and synthesis and will be published soon:

_ATG: Benchmarking Automated Theorem Generation for Generative Language Models_
https://openreview.net/forum?id=H0RzzhAxTv
(link available soon)

**Comment by j991222** [comment]
Hi,

Thanks for sharing your work! I've added both papers to the "Synthetic Theorem Generation" and "Benchmarks" sections.
