### ISSUE TITLE
Request to add reference

### ISSUE THREAD

**Issue by yinghy18** [j991222/ai4math-papers#2]
Hi, I believe this list is most helpful to us. Also it seems that out work is related to Autoformalization.

Our work for NIPS 2024 Dataset Track:
Lean Workbook: A large-scale Lean problem set formalized from natural language math problems 
https://arxiv.org/abs/2406.03847
With its dataset available: https://huggingface.co/datasets/internlm/Lean-Workbook

Would you mind adding this to the references? Thank you.

**Comment by j991222** [comment]
Hi,

Thanks for sharing your work. I've added your paper to the Autoformalization section.
